[[main]]
identifier = "about"
name = "About"
url = "about"
weight = 1

[[main]]
identifier = "ctfs"
name = "CTFs"
url = "ctfs"
weight = 2

# [[main]]
# identifier = "archive"
# name = "Archive"
# url = "archive"
# weight = 3

# [[main]]
# identifier = "talks"
# name = "Talks"
# url = "talks"
# reight = 4
